name: Build and Deploy OpenWRT Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y python2.7 python2.7-dev

      - name: Download and prepare OpenWRT SDK
        run: |
          wget -q https://downloads.openwrt.org/releases/19.07.7/targets/ar71xx/generic/openwrt-sdk-19.07.7-ar71xx-generic_gcc-7.5.0_musl.Linux-x86_64.tar.xz
          tar xJf openwrt-sdk-19.07.7-ar71xx-generic_gcc-7.5.0_musl.Linux-x86_64.tar.xz
          mv openwrt-sdk-19.07.7-ar71xx-generic_gcc-7.5.0_musl.Linux-x86_64 openwrt-sdk-19.07.7-ar71xx-generic
          
          cd openwrt-sdk-19.07.7-ar71xx-generic
          echo "src-link frieren ${{ github.workspace }}/packages/openwrt/19" >> feeds.conf
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          ./scripts/feeds install -p frieren frieren

      - name: Build package
        run: |
          cd openwrt-sdk-19.07.7-ar71xx-generic
          make package/frieren/download
          make package/frieren/compile

      - name: Move build output
        run: |
          mkdir -p ${{ github.workspace }}/compiled-packages/openwrt/19
          cp openwrt-sdk-19.07.7-ar71xx-generic/bin/packages/*/*/*.ipk ${{ github.workspace }}/compiled-packages/openwrt/19

      - name: Commit and push compiled packages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add compiled-packages/openwrt/19/*.ipk
          git commit -m "Automated build and deploy of OpenWRT package"
          git push
