name: Build and Deploy OpenWRT Package

on:
  workflow_dispatch:

jobs:
  build_legacy:
    runs-on: ubuntu-22.04
    env:
      SDK_TARGET_URL: https://downloads.openwrt.org/releases/19.07.7/targets/ar71xx/generic/openwrt-sdk-19.07.7-ar71xx-generic_gcc-7.5.0_musl.Linux-x86_64.tar.xz
      BUILD_DIR: ${{ github.workspace }}/build-env
      SDK_DIR: ${{ github.workspace }}/build-env/openwrt-sdk
      REPO_DIR: ${{ github.workspace }}/repo-source
      IPK_OUTPUT_DIR: ${{ github.workspace }}/repo-source/packages/openwrt/19

    steps:
      - name: Setup environment
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y python2.7 python2.7-dev

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'repo-source'

      - name: Download and prepare OpenWRT SDK
        run: |
          echo "[*] Downloading SDK..."
          wget -q $SDK_TARGET_URL -P $BUILD_DIR

          echo "[*] Prepare folder"
          tar xJf $BUILD_DIR/openwrt-sdk-19.07.7-ar71xx-generic_gcc-7.5.0_musl.Linux-x86_64.tar.xz -C $BUILD_DIR
          mv $BUILD_DIR/openwrt-sdk-19.07.7-ar71xx-generic_gcc-7.5.0_musl.Linux-x86_64 $SDK_DIR

      - name: Build package
        env:
          # try to fix "Build dependency: Please install the GNU C Compiler (gcc) 4.8 or later"
          FORCE: "1" 
        run: |
          echo "[*] Prepare feeds"
          cd $SDK_DIR
          echo "src-link frieren $REPO_DIR/src/openwrt/19" >> feeds.conf
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          ./scripts/feeds install -p frieren frieren

          echo "[*] Build ipk"
          echo "CONFIG_PACKAGE_frieren=m" >> .config
          make defconfig
          make -j1 V=s package/frieren/compile

      - name: Sync repos
        run: |
          cd $REPO_DIR
          git fetch origin master
          git rebase origin/master

      - name: Move build output
        run: |
          mkdir -p "$IPK_OUTPUT_DIR"
          cp $SDK_DIR/bin/packages/*/*/*.ipk "$IPK_OUTPUT_DIR/"

      - name: Commit and push compiled packages
        run: |
          cd $REPO_DIR
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add packages
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated build and deploy of OpenWRT legacy package"
            git push
          fi

  build:
    runs-on: ubuntu-22.04
    env:
      SDK_TARGET_URL: https://downloads.openwrt.org/releases/23.05.3/targets/ath79/generic/openwrt-sdk-23.05.3-ath79-generic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
      BUILD_DIR: ${{ github.workspace }}/build-env
      SDK_DIR: ${{ github.workspace }}/build-env/openwrt-sdk
      REPO_DIR: ${{ github.workspace }}/repo-source
      IPK_OUTPUT_DIR: ${{ github.workspace }}/repo-source/packages/openwrt/latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'repo-source'

      - name: Download and prepare OpenWRT SDK
        run: |
          echo "[*] Downloading SDK..."
          wget -q $SDK_TARGET_URL -P $BUILD_DIR

          echo "[*] Prepare folder"
          tar xJf $BUILD_DIR/openwrt-sdk-23.05.3-ath79-generic_gcc-12.3.0_musl.Linux-x86_64.tar.xz -C $BUILD_DIR
          mv $BUILD_DIR/openwrt-sdk-23.05.3-ath79-generic_gcc-12.3.0_musl.Linux-x86_64 $SDK_DIR

      - name: Build package
        run: |
          echo "[*] Prepare feeds"
          cd $SDK_DIR
          echo "src-link frieren $REPO_DIR/src/openwrt/latest" >> feeds.conf
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          ./scripts/feeds install -p frieren frieren

          echo "[*] Build ipk"
          echo "CONFIG_PACKAGE_frieren=m" >> .config
          make defconfig
          make -j1 V=s package/frieren/compile

      - name: Sync repos
        run: |
          cd $REPO_DIR
          git fetch origin master
          git rebase origin/master

      - name: Move build output
        run: |
          mkdir -p "$IPK_OUTPUT_DIR"
          cp $SDK_DIR/bin/packages/*/*/*.ipk "$IPK_OUTPUT_DIR/"

      - name: Commit and push compiled packages
        run: |
          cd $REPO_DIR
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add packages
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated build and deploy of OpenWRT package"
            git push
          fi
